### ISSUE TITLE
3 Features/Issues

### ISSUE THREAD

**Issue by chriskith** [chriskith/COMP-129-Individual-Project#2]
3 Features/Issues
Note: Commented on the previous issue thread that Professor Osvaldo posted, wasn't sure so I posted it as a new issue.

1. Adding power ups to the game. Powerups such as slowing down the movement speed of the pipes and invincibility which will make the character clip the pipes for 7 seconds. Powerups will be a new class and it will affect the PipeGeneration class. With slowtime, it will affect the pipe movement and that’s located in the PipeGeneration class. Same with invincibility because the collision detection is located in the class. As for the powerups spawning on the map, it should be done in PowerUps class itself. Will have to adjust the pipe spawn rate.
2. Implementing enemies to the game. Other than the pipes as the only obstacles, but stationary enemies that will spawn randomly. This will have the players determine the placement of the bird. For example This will be its own class known as Enemy. It will affect the PipeGeneration. I would need to fix the pipe spawn and adjust the spacing when the pipe spawns.
3. New bird skins will be implemented. A shop will need to implemented and that would need it’s own GraphicPane. It will need to be added to the menu pane as well. As an in game currency will need to be implemented. The score converter will determine how much in game currency you can receive.

**Comment by onzfonz** [comment]
So couple of things.  1) Do not use this project, you should hit the fork button on your actual project
https://github.com/comp55-fall18/group-project-osvaldo-s-sons
Click the fork button up top and then place the issues in there.  Use the settings button to turn on issues if they dont' show up.
2) Each of these numbered should be it's own issue, so I can comment on them separately.
3) I'd like you to work on the powerups one, but please do it from the forked repository that you'll create.  Once you do that, I can bring up your 55 resurrection pt 1 grade. 
Let me know if you have any questions.  Thanks!
